title: "Project_1"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

library(ggplot2)
library(plyr)

#Load the data 
data <- read.csv("activity.csv")
#Process/transform the data (if necessary) into a format suitable for your analysis
str(data)
head(data)
tail(data)
missing_data <- data[is.na(data$steps),]
dim(missing_data)

##What is mean total number of steps taken per day?
#Calculate the total number of steps
data2 <- data[!is.na(data$steps),]
total_steps <- with(data, tapply(steps, as.factor(data$date), sum, na.rm = T))
#Make a histogram of the total number of steps taken each day
hist(total_steps, main = "Histogram of total steps taken per day", xlab = "Total steps",)
#Calculate and report the mean and median of the total number of steps taken per day
Meantotal_steps <- mean(total_steps, na.rm = TRUE)
Mediantotal_steps <- median(total_steps, na.rm = TRUE)

##What is the average daily activity pattern?
#Make a time series plot of the 5-minute interval and the average number of steps taken, averaged across all days
mean_steps <- with(data2, tapply(steps, data2$interval, mean))
interval <- levels(as.factor(data2$interval))
plot(interval, mean_steps, type = "l", main = "Time series plot of the \n average steps taken", xlab = "interval", ylab = "Mean steps")

#Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
table <- data.frame(mean_steps, interval)
table[table$mean_steps==max(table$mean_steps),][2]

##Imputing missing values
#Calculate and report the total number of missing values in the dataset 
length(missing_data$steps)

#Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.
##I thing that replace the missing values by the the average number of steps taken, across all days.

#Create a new dataset that is equal to the original dataset but with the missing data filled in.

new_data <- rbind(data2, missing_data)
new_data <- new_data[order(new_data$date), ]

head(new_data, 12)

#Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?

total_steps2 <- with(new_data, tapply(steps, as.factor(new_data$date), sum))
hist(total_steps2, main = "histogram total steps taken per day", xlab = "Total steps")
summary(total_steps)
summary(total_steps2)
##mean and median differ between bought dataset.

#Are there differences in activity patterns between weekdays and weekends?

new_data$days <- weekdays(as.Date(new_data$date))
weekend_feature <- grep("Saturday|Sunday", new_data$days, ignore.case = T)
weekend_data<-  new_data[weekend_feature, ]
weekend_data$weekday <- "weekend"
weekday_data <- subset(new_data,new_data$days!=weekend_feature)
weekday_data$weekday <- "weekday"

new_data2 <- rbind(weekday_data, weekend_data)


